### ISSUE TITLE
entity: verify if regex entered in frontend is correct or not

### ISSUE THREAD

**Issue by lolo8304** [axa-group/nlp.js-app#15]
**Describe the bug**
validate entered regexp for regexp-entity because train is crashing if not

**To Reproduce**
1. Go to 'entity edit' dialog
2. enter "[a-zA-Z|]+[ ]*\d+"
3. Click on 'update'
4. train
5. train is running for ever and stack trace

**Expected behavior**
error message that regexp is wrong 
or always create valid rexexp from regex-string, if regex string is correct

example email
valid = /\b(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})\b/gi
invalid = \w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})

example above: car plate number
invalid = [a-zA-Z|]+[ ]*\d+
valid = /\b([a-zA-Z|]+[ ]*\d+)\b/gi

**Screenshots**
this is error in log:
Debug: internal, implementation, error 
    SyntaxError: Invalid flags supplied to RegExp constructor '[a-zA-Z|]+[ ]*\d+'
    at new RegExp (<anonymous>)
    at Function.str2regex (/Users/Lolo/git/nlp.js-app/node_modules/node-nlp/lib/ner/regex-named-entity.js:113:12)
    at RegexNamedEntity.addStrRegex (/Users/Lolo/git/nlp.js-app/node_modules/node-nlp/lib/ner/regex-named-entity.js:60:50)
    at NlpManager.addRegexEntity (/Users/Lolo/git/nlp.js-app/node_modules/node-nlp/lib/nlp/nlp-manager.js:145:14)
    at data.entities.forEach.entity (/Users/Lolo/git/nlp.js-app/server/trainers/nlpjs-trainer.js:50:17)
    at Array.forEach (<anonymous>)
    at NlpjsTrainer.addEntities (/Users/Lolo/git/nlp.js-app/server/trainers/nlpjs-trainer.js:32:19)
    at NlpjsTrainer.train (/Users/Lolo/git/nlp.js-app/server/trainers/nlpjs-trainer.js:120:10)
    at App.train (/Users/Lolo/git/nlp.js-app/server/app.js:128:37)
    at train (/Users/Lolo/git/nlp.js-app/server/feats/agent/agent.controllers.js:279:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version (master, alpha version)

**Additional context**

**Comment by ericzon** [comment]
Thanks for the information. PR (https://github.com/axa-group/nlp.js/pull/295) merged in nlp.js to add 'g' flag if not present. After a new release appear, it will be upgraded in the dashboard too.
We'll add a validation in the dashboard.

**Comment by ericzon** [comment]
Fixed in the latest update.
